import { useId, useState } from 'react';
import { geminiMockEnabled, useGeminiResearch, useSnowflakeResearch } from '../hooks/useAIResearch';
import { combineResearch, RESEARCH_DISCLAIMER } from '../api/researchDocument';
import { ResearchAudio } from './ResearchAudio';
import { PanelBoundary } from './PanelBoundary';
import { Panel, StateMessage, StatusBadge } from './ui';

/** Company/event changes discard all generated research, pending requests, and audio. */
export function AIResearchAssistant(props: { ticker: string; evidenceKey: string }) {
  return <ResearchAssistant key={`${props.ticker}:${props.evidenceKey}`} {...props} />;
}

function ResearchAssistant({ ticker, evidenceKey }: { ticker: string; evidenceKey: string }) {
  const id = useId();
  const [generation, setGeneration] = useState(0);
  const eventId = evidenceKey === 'no-event' ? undefined : `${ticker}:${evidenceKey}`;
  const context = useSnowflakeResearch(ticker, eventId);
  const explanation = useGeminiResearch(ticker);
  const pending = context.state === 'pending' || explanation.state === 'pending';
  const settled = !pending && context.state !== 'idle' && explanation.state !== 'idle';
  const document = settled ? combineResearch(context.result?.context ?? null, explanation.result) : null;
  function generate() {
    if (pending) return;
    // Both guarded requests start immediately; neither awaits the other.
    void context.generate();
    void explanation.generate();
    setGeneration(value => value + 1);
  }
  return <section className="ie-stack ie-research-assistant" aria-labelledby={`${id}-heading`}>
    <header className="ie-research-assistant-heading">
      <h2 id={`${id}-heading`}>AI Research Assistant</h2>
      {geminiMockEnabled() && <StatusBadge tone="info">Development mock - quantitative explanation is not generated by Gemini; real audio verification is unavailable.</StatusBadge>}
      {!document && <p className="ie-muted">{RESEARCH_DISCLAIMER}</p>}
    </header>
    <div className="ie-stack">
      <div><button className="ie-button ie-button--primary" onClick={generate} disabled={pending}>
        {pending ? 'Generating AI Research...' : 'Generate AI Research'}
      </button></div>
      <ul className="ie-research-assistant-progress" aria-live="polite">
        {[['Snowflake Cortex', context.state], ['Gemini', explanation.state]].map(([name, state]) =>
          <li key={name}>{name}: {state === 'success' ? 'Ready' : state === 'pending' ? 'Generating...' : state === 'error' ? 'Unavailable' : 'Not generated'}</li>)}
      </ul>
    </div>
    {settled && !document && <StateMessage kind="error" title="AI research unavailable">
      Neither provider returned research. Quantitative evidence remains available. Use Generate AI Research to retry.
    </StateMessage>}
    {document && <PanelBoundary key={generation} label="AI research document">
      <Panel title={document.title} className="ie-research-document">
        <div className="ie-stack">
          {document.sections.map(section => <section key={section.title}>
            <h3>{section.title}</h3>
            <ul>{section.items.map((text, index) => <li key={index}>{text}</li>)}</ul>
          </section>)}
          {document.unavailable.map(text => <p key={text} className="ie-muted" role="status">{text}</p>)}
          <div><p className="ie-muted">Research generated from:</p>
            <ul>{document.sources.map(source => <li key={source}>{source}</li>)}</ul>
          </div>
          <p className="ie-muted">{document.disclaimer}</p>
          {eventId ? <PanelBoundary label="Research audio"><ResearchAudio ticker={ticker} research={{
            research_event_id: eventId, document,
            ...(context.result?.context ? { snowflake_context: context.result.context } : {}),
            ...(explanation.result ? { gemini_explanation: explanation.result } : {}),
          }} /></PanelBoundary> : <p className="ie-muted">Audio requires a persisted research event.</p>}
        </div>
      </Panel>
    </PanelBoundary>}
  </section>;
}
