import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { explanationSections, isResearchText, mockExplanation, requestExplanation } from '../api/explain';
import type { ExplainResponse } from '../types/explain';
import { Panel, PanelSkeleton, StateMessage, StatusBadge } from './ui';

export function ExplanationSections({ explanation }: { explanation: ExplainResponse }) {
  return <div className="ie-explanation-sections ie-reveal">
    {explanationSections.map(([key, title]) => {
      const items = explanation[key].filter(isResearchText);
      const withheld = items.length !== explanation[key].length;
      return <section key={key}><h3>{title}</h3>
        {items.length ? <ul>{items.map((text, index) => <li key={index}>{text}</li>)}</ul> : <p className="ie-muted">No research evidence provided for this section.</p>}
        {withheld && <p className="ie-muted">Content outside the research explanation scope was withheld.</p>}
      </section>;
    })}
  </div>;
}

/** Quantitative evidence renders independently of all AI request states. */
export function ExplainSignal({ ticker, evidence, evidenceKey = ticker }: { ticker: string; evidence: ReactNode; evidenceKey?: string }) {
  return <div className="ie-stack">
    {evidence}
    <ExplanationRequest key={`${ticker}:${evidenceKey}`} ticker={ticker} />
  </div>;
}

function ExplanationRequest({ ticker }: { ticker: string }) {
  const [state, setState] = useState<'idle' | 'pending' | 'success' | 'error'>('idle');
  const [explanation, setExplanation] = useState<ExplainResponse | null>(null);
  const request = useRef<AbortController | null>(null);
  const resultId = useId();
  const mock = import.meta.env.DEV && import.meta.env.VITE_EXPLAIN_MOCK !== 'false';
  useEffect(() => () => {
    const active = request.current;
    request.current = null;
    active?.abort();
  }, []);
  async function explain() {
    if (request.current || state === 'success') return;
    const controller = new AbortController();
    request.current = controller;
    setState('pending');
    const timeout = window.setTimeout(() => controller.abort(), 20000);
    try {
      const result = mock ? mockExplanation(ticker) : await requestExplanation(ticker, controller.signal, import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000');
      if (request.current !== controller) return;
      if (controller.signal.aborted) throw new Error('Explanation timed out');
      setExplanation(result);
      setState('success');
    } catch {
      if (request.current === controller) setState('error');
    } finally {
      window.clearTimeout(timeout);
      if (request.current === controller) request.current = null;
    }
  }
  return <Panel title="AI explanation · Gemini" description="Gemini interprets existing quantitative evidence. It does not create the signal or change scores or predictions." actions={<StatusBadge tone="info">{mock ? 'Development mock · Not generated by Gemini' : 'AI interpretation'}</StatusBadge>}>
    <div className="ie-stack">
      <p className="ie-muted">For research review only. Compare the explanation with the quantitative evidence above.</p>
      <div><button className="ie-button ie-button--primary" onClick={explain} disabled={state === 'pending' || state === 'success'} aria-controls={resultId} aria-expanded={state !== 'idle'}>{state === 'pending' ? 'Explaining signal…' : state === 'success' ? 'Explanation loaded' : state === 'error' ? 'Retry Explain Signal' : 'Explain Signal'}</button></div>
      <div id={resultId}>
        {state === 'pending' && <PanelSkeleton label="Preparing AI explanation" rows={5} />}
        {state === 'error' && <StateMessage kind="error" title="AI explanation unavailable">Please retry. Score, CAR, statistics, and model evidence remain available above.</StateMessage>}
        {state === 'success' && explanation && <><p role="status" className="ie-sr-only">AI explanation ready.</p><ExplanationSections explanation={explanation} /></>}
      </div>
    </div>
  </Panel>;
}
